language: ruby
rvm:
  - 2.6.3

env:
  - JEKYLL_ENV=production

before_script:
 - chmod +x ./script/cibuild

script: ./script/cibuild

cache: bundler

after_success: |
    sudo pip install ghp-import && \
    ghp-import _site && \
    git push -qf https://${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages