# Site settings
title: Cryptography for steppen wolves
email: russo.1699981@studenti.uniroma1.it
description: A solitary place for steppen wolves, interested in crypto.
baseurl: "/steppen-wolf"
url: ""
github_username: lrusso96
github_repo: steppen-wolf

# Build settings
plugins:
  - jekyll-feed
  - jekyll-analytics
  - jekyll-sitemap

jekyll_analytics:
  GoogleAnalytics:
      id: UA-161565816-1
